### PR TITLE
Remove duplicated API and add qml example for current login user

### PR DESCRIPTION
**Pull request by xiangzhai**
Hi @plfiorini 

It is my fault ;P UserAccount`s default constructor is able to get current login user, so findUserIconFile in AccountsManager is duplicate, also the same story about userAccountChanged signal.

Regards,
Leslie Zhai

### CODE REVIEW

**Comment by plfiorini** [comment]
Could you please do one commit for the API and a second commit that adds the example with the copyright notice?

**Comment by plfiorini** [comment]
Also we should use GPL2+ for examples, here's a boilperplate header https://github.com/hawaii-desktop/repotools/blob/master/licenses/header.GPL2%2B

I will change the examples already part of the source tree later

**Comment by xiangzhai** [comment]
> Could you please do one commit for the API and a second commit that adds the example with the copyright notice?

how to ignore the second commit ;P

**Comment by plfiorini** [comment]
You should do the license changes, squash all commits together, reset and make two commits one for C++ and one for QML

**Comment by plfiorini** [comment]
Then git push -f to your branch, it will update the PR here

**Pull request closed without merging**
