### PR TITLE
Make findUserByName async

### PR DESCRIPTION
**Pull request by xiangzhai**

### CODE REVIEW

**Comment by plfiorini** [comment]
Please rebase to latest master with:
```
git fetch origin
git rebase origin/master
```

and force push

**Comment by xiangzhai** [comment]
> Please rebase to latest master with:

git fetch origin
git rebase origin/master
and force push

done ;-)

**Comment by plfiorini** [comment]
The PR is a bit messy, I will probably end up cherry-picking.
It's better if you keep your master in sync with upstream and always work on another branch detached from master. This way when the changes are integrated here you just delete the new branch and then you git pull master in order to get the latest from here and when you need to do new changes you create a new branch from that point.

**Comment by plfiorini** [comment]
Ok merged the commits with the aforementioned fixes

**Pull request closed without merging**
