### PR TITLE
Remove qt5 Gui dependence, add findUserIconFile for QML easy-to-use, and will migrate to the latest AccountsService DBus interface.

### PR DESCRIPTION
**Pull request by xiangzhai**
Hi @plfiorini please pay some attention to my patch, thanks a lot ;-)

Regards,
Leslie Zhai - a KDE developer https://identity.kde.org/index.php?r=people/view&uid=lesliezhai

### CODE REVIEW

**Comment by plfiorini** [comment]
Merged, oh btw thanks for the PR.
Another thing to do is to use the new fancy cmake stuff for the library much like https://github.com/greenisland/greenisland/libgreenisland does

**Comment by xiangzhai** [comment]
Sorry https://github.com/greenisland/greenisland/libgreenisland is not available?

I will learn about KDE`s cmake ;P

**Comment by plfiorini** [comment]
@xiangzhai Yep I realized the path was wrong and edited my comment.
Anyway QtAccountsService now uses the new cmake macros to make the cmake package and camel case headers. I had to change the namespace to QtAccountsService though (just AccountsService seemed too generic).

Basically what is left to do here is:
- Add new accountsservice features if any
- Maybe remove the Qt5::Gui dependency, it's needed because the model expose the picture so we might want to only expose the path and remove the Qt5::Gui dependency.
- Add unit tests
- Release

**Comment by xiangzhai** [comment]
@plfiorini cool!

**Pull request merged**
