### PR TITLE
Remove duplicate API && add qml example for current login user

### PR DESCRIPTION
**Pull request by xiangzhai**
Hi @plfiorini 

I am not familiar with github, so I just git revert, then commit && push, hope it is correct.

Regards,
Leslie Zhai

### CODE REVIEW

**Comment by plfiorini** [comment]
I'll if I can fix the PR locally for you

**Comment by plfiorini** [comment]
git rebase -i HEAD~7, remove the first 4 commits then git push -f

@xiangzhai Do you agree on picking "GPL2 or (at your option) any later version" license for the example?

**Comment by xiangzhai** [comment]
Hi @plfiorini I agree ;-) I just copy the copyright from your listusers.qml example ;P

**Comment by plfiorini** [comment]
merged

**Comment by xiangzhai** [comment]
Thanks ;-)

**Pull request closed without merging**
